version: '3'
services:
  pterodactyl:
    build: .
    container_name: pterodactyl_panel
    restart: always
    ports:
      - "8080:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost:8080
    volumes:
      - ./pterodactyl:/var/www/pterodactyl
